### ISSUE TITLE
Failed to load resource: /client-a/main.bundle.js

### ISSUE THREAD

**Issue by GzimH** [manfredsteyer/angular-microapp#9]
Firstly, thank you for putting the work on this repo, its much appreciated.

Issue: After cloning your repo and running it, the app can't load the web components client-a and client-b
![image](https://user-images.githubusercontent.com/18744740/44960407-a4d33a00-aeff-11e8-8c09-f337427c8d9c.png)

Steps to reproduce:
1.  Clone the repo
2. npm run build 
3. npm start

**Comment by Saiteja3963** [comment]
How did you overcome this issue? @GzimH
